[package]
name = "surf-governor"
description = "A rate-limiting middleware for surf"
version = "0.1.0"
edition = "2021"

[dependencies]
governor = "0.4.2"
http-types = "2.12.0"
lazy_static = "1.4.0"
surf = "2.3.2"

[dev-dependencies]
async-std = { version = "1.11.0", features = ["attributes"] }
url = "2.2.2"
